"""updated domain

Revision ID: 0a84a1800084
Revises: bc3cdacb67f0
Create Date: 2026-02-22 11:37:37.829541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a84a1800084'
down_revision = 'bc3cdacb67f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_inquiries_email'), ['email'], unique=False)

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('record_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deposit_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.alter_column('domain_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcriptions', schema=None) as batch_op:
        batch_op.alter_column('domain_features',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('deposit_amount')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('record_count')

    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_inquiries_email'))

    op.drop_table('contact_inquiries')
    # ### end Alembic commands ###
