"""Add target_goal and activation fields to domain

Revision ID: 0aaecba4f34c
Revises: 
Create Date: 2026-02-12 17:38:06.069086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aaecba4f34c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('Ai_confidence', sa.Float(), nullable=True))
        batch_op.drop_constraint(batch_op.f('datasets_ref_number_fkey'), type_='foreignkey')

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('total_budget', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_goal', sa.Integer(), nullable=False,server_default='100'))
        batch_op.add_column(sa.Column('is_automated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('is_automated')
        batch_op.drop_column('target_goal')
        batch_op.drop_column('total_budget')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('datasets_ref_number_fkey'), 'DomainOwner', ['ref_number'], ['reference_number'])
        batch_op.drop_column('Ai_confidence')
        batch_op.drop_column('collector_id')

    # ### end Alembic commands ###
