"""empty message

Revision ID: 165158d0020d
Revises: aac83c19584f
Create Date: 2026-06-19 12:14:39.008371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165158d0020d'
down_revision = 'aac83c19584f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_disbursement', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['transaction_note'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_disbursement', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
