"""Add is_suspended column to Users

Revision ID: 1a530777c556
Revises: merge_e1f4_fb5ac
Create Date: 2026-08-23 17:09:53.026130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a530777c556'
down_revision = 'merge_e1f4_fb5ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=False,server_default='false'))

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'Users', ['actor_id'], ['id'])

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paused', sa.Boolean(), nullable=False,server_default='false'))
        batch_op.add_column(sa.Column('rate_per_submission', sa.Float(), nullable=False,server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('rate_per_submission')
        batch_op.drop_column('is_paused')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
