"""add allow_community_posts to community_posts

Revision ID: 1acde2c360a6
Revises: d2ce78b324b5
Create Date: 2026-07-07 11:52:10.712130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1acde2c360a6'
down_revision = 'd2ce78b324b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_withdrawal_requests_collector'))

    op.drop_table('withdrawal_requests')
    with op.batch_alter_table('community_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_author'))
        batch_op.drop_index(batch_op.f('ix_responses_post'))
        batch_op.drop_index(batch_op.f('ix_responses_upvotes'))

    op.drop_table('community_responses')
    with op.batch_alter_table('collector_earnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collector_earnings_collector'))

    op.drop_table('collector_earnings')
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_community_posts', sa.Boolean(), nullable=True))
        batch_op.alter_column('reward_description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_community_posts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_is_pinned'), ['is_pinned'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_posts_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created_at'))
        batch_op.alter_column('reward_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('allow_community_posts')

    op.create_table('collector_earnings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quality_multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'earned'::character varying"), autoincrement=False, nullable=True),
    sa.Column('transaction_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['Users.id'], name=op.f('collector_earnings_collector_id_fkey')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('collector_earnings_dataset_id_fkey')),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name=op.f('collector_earnings_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collector_earnings_pkey'))
    )
    with op.batch_alter_table('collector_earnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collector_earnings_collector'), ['collector_id'], unique=False)

    op.create_table('community_responses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('upvotes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Users.id'], name=op.f('community_responses_author_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], name=op.f('community_responses_post_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('community_responses_pkey'))
    )
    with op.batch_alter_table('community_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_responses_upvotes'), [sa.literal_column('upvotes DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_post'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_author'), ['author_id'], unique=False)

    op.create_table('withdrawal_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('gateway', sa.VARCHAR(length=20), server_default=sa.text("'MPESA'::character varying"), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('paypal_email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=True),
    sa.Column('reference', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('requested_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['Users.id'], name=op.f('withdrawal_requests_collector_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('withdrawal_requests_pkey'))
    )
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_withdrawal_requests_collector'), ['collector_id'], unique=False)

    # ### end Alembic commands ###
