"""Fresh start on Postgres

Revision ID: 21b51d88ce77
Revises: 
Create Date: 2026-02-25 08:15:44.854193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b51d88ce77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DomainOwner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('domain_field', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reference_number'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('DomainOwner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DomainOwner_domain_field'), ['domain_field'], unique=False)
        batch_op.create_index(batch_op.f('ix_DomainOwner_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_DomainOwner_last_name'), ['last_name'], unique=False)

    op.create_table('contact_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_inquiries_email'), ['email'], unique=False)

    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('domain_name', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('deposit_amount', sa.Float(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('target_goal', sa.Integer(), nullable=False),
    sa.Column('is_automated', sa.Boolean(), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_domain_name'), ['domain_name'], unique=False)

    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('domain_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['reference_number'], ['domain.reference_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_second_name'), ['second_name'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('combined_text', sa.Text(), nullable=True),
    sa.Column('segmented_text', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('Ai_confidence', sa.Float(), nullable=True),
    sa.Column('audio_file_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index('ix_dataset_owner_domain', ['owner_id', 'domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_domain_id'), ['domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)

    op.create_table('domain_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('domain_owner_id', sa.Integer(), nullable=True),
    sa.Column('specialization_required', sa.String(length=255), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('estimated_submissions', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['domain_owner_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_ref', sa.String(length=100), nullable=True),
    sa.Column('checkout_request_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_checkout_request_id'), ['checkout_request_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_transaction_ref'), ['transaction_ref'], unique=True)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('relevant_experience', sa.Text(), nullable=True),
    sa.Column('self_assessment_skills', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('reference_number_assigned', sa.String(length=255), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contributor_name', sa.String(length=100), nullable=False),
    sa.Column('transcription_text', sa.Text(), nullable=False),
    sa.Column('domain_features', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcriptions')
    op.drop_table('job_applications')
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_ref'))
        batch_op.drop_index(batch_op.f('ix_payment_checkout_request_id'))

    op.drop_table('payment')
    op.drop_table('jobs')
    op.drop_table('domain_features')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_domain_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_created_at'))
        batch_op.drop_index('ix_dataset_owner_domain')

    op.drop_table('datasets')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_second_name'))
        batch_op.drop_index(batch_op.f('ix_Users_first_name'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_domain_name'))

    op.drop_table('domain')
    with op.batch_alter_table('contact_inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_inquiries_email'))

    op.drop_table('contact_inquiries')
    with op.batch_alter_table('DomainOwner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DomainOwner_last_name'))
        batch_op.drop_index(batch_op.f('ix_DomainOwner_first_name'))
        batch_op.drop_index(batch_op.f('ix_DomainOwner_domain_field'))

    op.drop_table('DomainOwner')
    # ### end Alembic commands ###
