"""updated the database

Revision ID: 3fcd0d417ca5
Revises: 5b28eb0ad399
Create Date: 2026-02-18 10:05:31.764533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcd0d417ca5'
down_revision = '5b28eb0ad399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('requirements')

    # ### end Alembic commands ###
