"""updates on job model

Revision ID: 5adea2bf061c
Revises: add_reviewed_by_user_id
Create Date: 2026-03-05 20:59:03.406836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5adea2bf061c'
down_revision = 'add_reviewed_by_user_id'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_jobapplications_reviewed_by_user'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['reviewed_by_user_id'], ['id'])

    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain_name', sa.String(length=255), nullable=True))
        batch_op.alter_column('specialization_required',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.alter_column('specialization_required',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('domain_name')

    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_jobapplications_reviewed_by_user'), 'Users', ['reviewed_by_user_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###
