"""add assigned_user_id to domain

Revision ID: 661ca8d71ec9
Revises: 165158d0020d
Create Date: 2026-06-25 05:25:34.296231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661ca8d71ec9'
down_revision = '165158d0020d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_locked_by'), ['locked_by'], unique=False)
        batch_op.drop_constraint(batch_op.f('fk_datasets_locked_by'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Users', ['locked_by'], ['id'])

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Users', ['assigned_user_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_collector_id_fkey'), type_='foreignkey')
        batch_op.drop_column('collector_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payment_collector_id_fkey'), 'Users', ['collector_id'], ['id'])

    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_user_id')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_datasets_locked_by'), 'Users', ['locked_by'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_datasets_locked_by'))

    # ### end Alembic commands ###
