"""updates on the phone_number

Revision ID: 6ae573806d54
Revises: 0a84a1800084
Create Date: 2026-02-22 12:04:11.971736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae573806d54'
down_revision = '0a84a1800084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
