"""Realigned community_posts relationship

Revision ID: 6d47aa3f0de7
Revises: b8bbd4bf1782
Create Date: 2026-05-01 23:59:29.799577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d47aa3f0de7'
down_revision = 'b8bbd4bf1782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=False),
    sa.Column('snippet', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.alter_column('author_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'community'::character varying"))
        batch_op.drop_index(batch_op.f('ix_community_posts_author'))
        batch_op.drop_index(batch_op.f('ix_community_posts_created'))
        batch_op.drop_index(batch_op.f('ix_community_posts_type'))
        batch_op.create_foreign_key(None, 'Users', ['author_id'], ['id'])
        batch_op.drop_column('reply_count')

    with op.batch_alter_table('quality_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('flag_reason', sa.Text(), nullable=False))
        batch_op.create_foreign_key(None, 'community_posts', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'Users', ['author_id'], ['id'])
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('description')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_flags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('resolved_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('author_id')
        batch_op.drop_column('post_id')

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reply_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_community_posts_type'), ['post_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_created'), [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_community_posts_author'), ['author_id'], unique=False)
        batch_op.alter_column('author_type',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'community'::character varying"))

    op.drop_table('comment')
    op.drop_table('inbox_message')
    # ### end Alembic commands ###
