"""Updates on jobapplication

Revision ID: 87708464c8b9
Revises: 5adea2bf061c
Create Date: 2026-03-07 13:53:53.713861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87708464c8b9'
down_revision = '5adea2bf061c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('second_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_column('second_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
