"""added payment columns to domain

Revision ID: a5b93b403266
Revises: 0aaecba4f34c
Create Date: 2026-02-15 10:46:30.434825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5b93b403266'
down_revision = '0aaecba4f34c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
