"""empty message

Revision ID: b897a2b2ed14
Revises: 1acde2c360a6
Create Date: 2026-07-26 07:54:20.884803

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b897a2b2ed14'
down_revision = '1acde2c360a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collector_earnings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collector_earnings_collector'))
        batch_op.drop_index(batch_op.f('ix_collector_earnings_dataset'))

    op.drop_table('collector_earnings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_earnings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('collector_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('quality_multiplier', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('1.0'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'earned'::character varying"), autoincrement=False, nullable=True),
    sa.Column('transaction_ref', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('processed_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collector_id'], ['Users.id'], name=op.f('collector_earnings_collector_id_fkey')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('collector_earnings_dataset_id_fkey')),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], name=op.f('collector_earnings_domain_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('collector_earnings_pkey'))
    )
    with op.batch_alter_table('collector_earnings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collector_earnings_dataset'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collector_earnings_collector'), ['collector_id'], unique=False)

    op.drop_table('community_responses')
    # ### end Alembic commands ###
