"""Add attachment field to CommunityPost

Revision ID: caf02c950acb
Revises: 6d47aa3f0de7
Create Date: 2026-05-02 00:17:11.497433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf02c950acb'
down_revision = '6d47aa3f0de7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###
