"""added the owner id

Revision ID: d8e703b2dc75
Revises: 6ae573806d54
Create Date: 2026-02-22 13:07:18.491920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e703b2dc75'
down_revision = '6ae573806d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_dataset_owner_domain', ['owner_id', 'domain_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'DomainOwner', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_datasets_owner_id'))
        batch_op.drop_index('ix_dataset_owner_domain')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
