"""empty message

Revision ID: dcb0cc5f8700
Revises: 
Create Date: 2026-01-30 15:04:48.580482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb0cc5f8700'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DomainOwner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('domain_field', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('reference_number'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('DomainOwner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_DomainOwner_domain_field'), ['domain_field'], unique=False)
        batch_op.create_index(batch_op.f('ix_DomainOwner_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_DomainOwner_last_name'), ['last_name'], unique=False)

    op.create_table('Domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=128), nullable=True),
    sa.Column('reference_number', sa.Integer(), nullable=True),
    sa.Column('domain_features', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['DomainOwner.id'], ),
    sa.ForeignKeyConstraint(['reference_number'], ['DomainOwner.reference_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference_number')
    )
    with op.batch_alter_table('Domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Domain_domain_name'), ['domain_name'], unique=False)

    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('second_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('domain_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('reference_number', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['reference_number'], ['Domain.reference_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_Users_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_Users_second_name'), ['second_name'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('ref_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('combined_text', sa.Text(), nullable=True),
    sa.Column('segmented_text', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['Domain.id'], ),
    sa.ForeignKeyConstraint(['ref_number'], ['DomainOwner.reference_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contributor_name', sa.String(length=100), nullable=False),
    sa.Column('transcription_text', sa.Text(), nullable=False),
    sa.Column('domain_features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transcriptions')
    op.drop_table('datasets')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Users_second_name'))
        batch_op.drop_index(batch_op.f('ix_Users_first_name'))
        batch_op.drop_index(batch_op.f('ix_Users_email'))

    op.drop_table('Users')
    with op.batch_alter_table('Domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Domain_domain_name'))

    op.drop_table('Domain')
    with op.batch_alter_table('DomainOwner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_DomainOwner_last_name'))
        batch_op.drop_index(batch_op.f('ix_DomainOwner_first_name'))
        batch_op.drop_index(batch_op.f('ix_DomainOwner_domain_field'))

    op.drop_table('DomainOwner')
    # ### end Alembic commands ###
