"""job&jobApplication

Revision ID: ecfb0db47d95
Revises: d8e703b2dc75
Create Date: 2026-02-23 16:43:13.164537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfb0db47d95'
down_revision = 'd8e703b2dc75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('domain_owner_id', sa.Integer(), nullable=True),
    sa.Column('specialization_required', sa.String(length=255), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('estimated_submissions', sa.Integer(), nullable=True),
    sa.Column('compensation', sa.String(length=255), nullable=True),
    sa.Column('duration', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['domain_owner_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('cv_file_path', sa.String(length=500), nullable=True),
    sa.Column('relevant_experience', sa.Text(), nullable=True),
    sa.Column('self_assessment_skills', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('approval_notes', sa.Text(), nullable=True),
    sa.Column('reference_number_assigned', sa.String(length=255), nullable=True),
    sa.Column('assigned_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['DomainOwner.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_applications')
    op.drop_table('jobs')
    # ### end Alembic commands ###
