"""Add payment gateway fields to User model

Revision ID: f8881c987ee1
Revises: f37532bd6579
Create Date: 2026-06-26 10:41:24.121450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8881c987ee1'
down_revision = 'f37532bd6579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_gateway', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('preferred_gateway')

    # ### end Alembic commands ###
