"""Add upvotes to community_posts

Revision ID: fb5accc5833a
Revises: cfd5d4e5c7b1
Create Date: 2026-08-18 23:42:52.720846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5accc5833a'
down_revision = 'cfd5d4e5c7b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response_upvotes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['community_responses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'response_id')
    )
    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upvotes', sa.Integer(), nullable=True))

    with op.batch_alter_table('community_responses', schema=None) as batch_op:
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('community_responses_user_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('community_responses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('community_responses_user_id_fkey'), 'Users', ['user_id'], ['id'])
        batch_op.alter_column('author_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('community_posts', schema=None) as batch_op:
        batch_op.drop_column('upvotes')

    op.drop_table('response_upvotes')
    # ### end Alembic commands ###
